"""Primera vesion estable

Revision ID: 03ae695d6b94
Revises: 031006e8f61a
Create Date: 2021-12-05 19:11:08.380322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ae695d6b94'
down_revision = '031006e8f61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
