"""Add iteraciones para eliminacion en results y prediction de version estable

Revision ID: 066d652dab8a
Revises: b06f65b1c7f8
Create Date: 2021-12-06 05:43:32.182684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066d652dab8a'
down_revision = 'b06f65b1c7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_results', sa.Column('iteraciones_para_eliminación', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_results', 'iteraciones_para_eliminación')
    # ### end Alembic commands ###
