"""Delete expire_at and add active_survey from Survey

Revision ID: 0a752d49152f
Revises: 279807e4c627
Create Date: 2021-10-30 05:48:47.128586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a752d49152f'
down_revision = '279807e4c627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('active_survey', sa.Boolean(), nullable=True))
    op.drop_column('survey', 'expire_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('expire_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('survey', 'active_survey')
    # ### end Alembic commands ###
