"""tecera revision

Revision ID: 0d8763b22790
Revises: 6046d4bcd198
Create Date: 2021-12-05 08:53:46.591849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8763b22790'
down_revision = '6046d4bcd198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
