"""Quit nullable false in question

Revision ID: 0e4ce952a42b
Revises: 721f1d598ff1
Create Date: 2021-11-03 21:26:03.003136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4ce952a42b'
down_revision = '721f1d598ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('question', 'accept_open_answer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('question', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('question', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('question', 'accept_open_answer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('question', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
