"""add index to title at Survey

Revision ID: 406303b6e85d
Revises: f92a39892ea5
Create Date: 2021-10-30 06:06:51.657536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406303b6e85d'
down_revision = 'f92a39892ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_survey_title'), 'survey', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_title'), table_name='survey')
    op.alter_column('survey', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
