"""Solve reverse property in question

Revision ID: 47df6d534ca9
Revises: b1a3548938d4
Create Date: 2021-11-18 20:15:23.625025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47df6d534ca9'
down_revision = 'b1a3548938d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
