"""Add description at Survey

Revision ID: 4e72578c24bf
Revises: 90d6d2351e54
Create Date: 2021-10-31 21:20:24.075511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e72578c24bf'
down_revision = '90d6d2351e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'description')
    # ### end Alembic commands ###
