"""Segunda revision

Revision ID: 6046d4bcd198
Revises: d00ba382c8c2
Create Date: 2021-12-05 08:53:23.083403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6046d4bcd198'
down_revision = 'd00ba382c8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answer_option', ['respondent_id', 'option_id', 'option_question_id', 'option_question_survey_id'])
    op.create_unique_constraint(None, 'answer_option_open', ['respondent_id', 'option_id', 'option_question_id', 'option_question_survey_id'])
    op.create_unique_constraint(None, 'question', ['id', 'survey_id'])
    op.create_unique_constraint(None, 'question_option', ['id', 'question_id', 'question_survey_id'])
    op.create_unique_constraint(None, 'question_option_open', ['id', 'question_id', 'question_survey_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_option_open', type_='unique')
    op.drop_constraint(None, 'question_option', type_='unique')
    op.drop_constraint(None, 'question', type_='unique')
    op.drop_constraint(None, 'answer_option_open', type_='unique')
    op.drop_constraint(None, 'answer_option', type_='unique')
    # ### end Alembic commands ###
