"""Correccion atributo answeroption

Revision ID: 62db7a49b460
Revises: 9dee2f06cd9c
Create Date: 2021-12-07 04:00:21.884015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62db7a49b460'
down_revision = '9dee2f06cd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_option', sa.Column('weight_selected', sa.Integer(), nullable=False))
    op.drop_column('answer_option', 'weight_elected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_option', sa.Column('weight_elected', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('answer_option', 'weight_selected')
    # ### end Alembic commands ###
