"""Segunda revision de version estable

Revision ID: 64c4c0d8476c
Revises: fa5728afcb24
Create Date: 2021-12-05 19:53:52.053369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c4c0d8476c'
down_revision = 'fa5728afcb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prediction_manual_id', table_name='prediction_manual')
    op.create_index(op.f('ix_prediction_manual_id'), 'prediction_manual', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_manual_id'), table_name='prediction_manual')
    op.create_index('ix_prediction_manual_id', 'prediction_manual', ['id'], unique=False)
    # ### end Alembic commands ###
