"""Add changes in question

Revision ID: 721f1d598ff1
Revises: bbf867a23974
Create Date: 2021-11-03 20:51:06.247191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721f1d598ff1'
down_revision = 'bbf867a23974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_option', sa.Column('option', sa.Text(), nullable=False))
    op.drop_column('question_option', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_option', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('question_option', 'option')
    # ### end Alembic commands ###
