"""Correcion atributo de aceptación

Revision ID: 74a410ceaffa
Revises: 8927bf9891fe
Create Date: 2021-12-07 08:27:30.221822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a410ceaffa'
down_revision = '8927bf9891fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
