"""Crear tabla de aceptación

Revision ID: 8927bf9891fe
Revises: 967e42ef19b2
Create Date: 2021-12-07 06:07:48.618490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8927bf9891fe'
down_revision = '967e42ef19b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_aceptacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('respondet_id', sa.Integer(), nullable=False),
    sa.Column('aceptacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_aceptacion_id'), 'survey_aceptacion', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_aceptacion_id'), table_name='survey_aceptacion')
    op.drop_table('survey_aceptacion')
    # ### end Alembic commands ###
