"""add on delete and update

Revision ID: 90fec81aae5c
Revises: b93f6bbb04d9
Create Date: 2021-12-08 07:54:57.827245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fec81aae5c'
down_revision = 'b93f6bbb04d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_option_question_id_fkey', 'question_option', type_='foreignkey')
    op.create_foreign_key(None, 'question_option', 'question', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('question_option_open_question_id_fkey', 'question_option_open', type_='foreignkey')
    op.create_foreign_key(None, 'question_option_open', 'question', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_option_open', type_='foreignkey')
    op.create_foreign_key('question_option_open_question_id_fkey', 'question_option_open', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'question_option', type_='foreignkey')
    op.create_foreign_key('question_option_question_id_fkey', 'question_option', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
