"""Crear tabla de aceptación

Revision ID: 967e42ef19b2
Revises: 62db7a49b460
Create Date: 2021-12-07 05:57:16.522367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967e42ef19b2'
down_revision = '62db7a49b460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_results', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_results', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
