"""Limit relation one to one in question with question_option_open

Revision ID: a894b6acf902
Revises: 47df6d534ca9
Create Date: 2021-11-18 21:20:40.715249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a894b6acf902'
down_revision = '47df6d534ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
