"""Tercea revision de version estable

Revision ID: b06f65b1c7f8
Revises: 64c4c0d8476c
Create Date: 2021-12-05 20:02:40.212516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06f65b1c7f8'
down_revision = '64c4c0d8476c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
