"""Quit question_option

Revision ID: b0c9aaad9534
Revises: 0e4ce952a42b
Create Date: 2021-11-18 02:31:31.058357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c9aaad9534'
down_revision = '0e4ce952a42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('question', 'accept_open_answer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('question', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('question', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_question_question'), 'question', ['question'], unique=False)
    op.create_index(op.f('ix_question_survey_id'), 'question', ['survey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_survey_id'), table_name='question')
    op.drop_index(op.f('ix_question_question'), table_name='question')
    op.alter_column('question', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('question', 'accept_open_answer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('question', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
