"""Check all changes

Revision ID: b1a3548938d4
Revises: 2cd37bd3a974
Create Date: 2021-11-18 06:44:14.944622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a3548938d4'
down_revision = '2cd37bd3a974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
