"""Correcion atributo de aceptación

Revision ID: b93f6bbb04d9
Revises: 74a410ceaffa
Create Date: 2021-12-07 08:27:52.333868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93f6bbb04d9'
down_revision = '74a410ceaffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_aceptacion', sa.Column('respondent_id', sa.Integer(), nullable=False))
    op.drop_column('survey_aceptacion', 'respondet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_aceptacion', sa.Column('respondet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('survey_aceptacion', 'respondent_id')
    # ### end Alembic commands ###
