"""Change Text and option name at Question, Question_option and Survey

Revision ID: bbf867a23974
Revises: 4e72578c24bf
Create Date: 2021-10-31 22:20:59.547458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf867a23974'
down_revision = '4e72578c24bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_option', sa.Column('option_name', sa.String(length=3), nullable=False))
    op.drop_column('question_option', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_option', sa.Column('name', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_column('question_option', 'option_name')
    # ### end Alembic commands ###
