"""Add Survey id at Question_option

Revision ID: e0d1f237081c
Revises: b0c9aaad9534
Create Date: 2021-11-18 04:02:03.759519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d1f237081c'
down_revision = 'b0c9aaad9534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_option', sa.Column('question_survey_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_option', 'question_survey_id')
    # ### end Alembic commands ###
