"""Add autoincrement test id in question

Revision ID: ea7e1c1130a9
Revises: a894b6acf902
Create Date: 2021-11-18 21:31:52.957401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7e1c1130a9'
down_revision = 'a894b6acf902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
