"""First version sisprel db

Revision ID: f5c57b836f5b
Revises: 
Create Date: 2021-11-26 22:00:38.336218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c57b836f5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('active_survey', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    op.create_index(op.f('ix_survey_title'), 'survey', ['title'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('accept_open_answer', sa.Boolean(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id', 'survey_id'),
    sa.UniqueConstraint('id', 'survey_id', name='Question_survey_unique_code')
    )
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    op.create_index(op.f('ix_question_question'), 'question', ['question'], unique=False)
    op.create_index(op.f('ix_question_survey_id'), 'question', ['survey_id'], unique=False)
    op.create_table('question_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_name', sa.String(length=3), nullable=False),
    sa.Column('option', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_survey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id', 'question_survey_id'], ['question.id', 'question.survey_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_option_id'), 'question_option', ['id'], unique=False)
    op.create_table('question_option_open',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_max', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_survey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id', 'question_survey_id'], ['question.id', 'question.survey_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_option_open_id'), 'question_option_open', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_option_open_id'), table_name='question_option_open')
    op.drop_table('question_option_open')
    op.drop_index(op.f('ix_question_option_id'), table_name='question_option')
    op.drop_table('question_option')
    op.drop_index(op.f('ix_question_survey_id'), table_name='question')
    op.drop_index(op.f('ix_question_question'), table_name='question')
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_survey_title'), table_name='survey')
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.drop_table('survey')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
