"""Primera revision de version estable

Revision ID: fa5728afcb24
Revises: 03ae695d6b94
Create Date: 2021-12-05 19:49:45.533655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5728afcb24'
down_revision = '03ae695d6b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
