default_context:
  project_name: 'SISPREL'
  project_slug: 'sisprel'
  domain_main: 'sisprel.com'
  domain_staging: 'stag.sisprel.com'
  docker_swarm_stack_name_main: 'sisprel-com'
  docker_swarm_stack_name_staging: 'stag-sisprel-com'
  secret_key: 'f720c1bb707d11500f965a58b375b0dad11de2436523b6e98c80730978ca2fd6'
  first_superuser: 'admin@sisprel.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.sisprel.com", "https://stag.sisprel.com", "https://sisprel.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.gmail.com'
  smtp_user: 'josuehernandezr082@gmail.com'
  smtp_password: 'pokemonzafir0'
  smtp_emails_from_email: 'info@sisprel.com'
  postgres_password: 'root'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: 'root'
  traefik_constraint_tag: 'sisprel.com'
  traefik_constraint_tag_staging: 'stag.sisprel.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: 'https://2919653404354bae90b4180f83421a60@o1051824.ingest.sentry.io/6035045'
  docker_image_prefix: ''
  docker_image_backend: 'sisprel'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
